# Module to generate dictionaries used for web display on super-donor.com
# Nathan VC 7/2016

# Generate dictionary for display of sperm bank names
# Key is the Field that appears in the dsr_db database
def gen_bank_dict():
    bank_dict={}
    bank_dict['AndroNW']='Andrology Northwest Laboratory'
    bank_dict['AnnArbor']='Ann Arbor Reproductive Assoc'
    bank_dict['Biogenetics']='Biogenetics'
    bank_dict['BosIVF']='Boston IVF'
    bank_dict['Canam']='Can-Am Cryo'
    bank_dict['CCB']='California CryoBank'
    bank_dict['Cryobio']='Cryobiology'
    bank_dict['CryogamCO']='Cryogam Colorado'
    bank_dict['Cryogen']='Cryogenic Laboratory'
    bank_dict['Cryos']='Cryos International'
    bank_dict['CryosNY']='Cryos NY'
    bank_dict['EBMC']='East Bay Medical Center'
    bank_dict['ESB']='European Sperm Bank USA'
    bank_dict['Fairfax']='Fairfax'
    bank_dict['FCCA']='Fertility center of CA'
    bank_dict['FertFirst']='Fertility First'
    bank_dict['FINO']='Fertility Institute of New Orleans'
    bank_dict['Follas']='Follas Laboratories, Inc.'
    bank_dict['GeorgiaRS']='Georgia Reproductive Specialists'
    bank_dict['GG']='Growing Generations'
    bank_dict['HC']='Heredity Choice'
    bank_dict['Idant']='Idant'
    bank_dict['IntCryo']='International Cryogenics'
    bank_dict['MSB']='Manhattan Sperm Bank'
    bank_dict['Midwest']='Midwest Sperm Bank'
    bank_dict['NECC']='New England Cryogenic Center'
    bank_dict['NoCASB']='Northern CA Sperm Bank'
    bank_dict['NWCryo']='Northwest Cryobank'
    bank_dict['OHSU']='Oregon Health & Science University'
    bank_dict['Paces']='Paces'
    bank_dict['PRS']='Pacific Reproductive Services'
    bank_dict['ProTech']='Procreative Technologies'
    bank_dict['RepGerm']='Repository for Germinal Choice'
    bank_dict['Reprolab']='Repro Lab, Inc.'
    bank_dict['ReproRes']='Reproductive Resources'
    bank_dict['Repromed']='Repromed'
    bank_dict['RochReg']='Rochester Regional'
    bank_dict['RMC']='Rocky Mountain Cryobank'
    bank_dict['TSBC']='The Sperm Bank of CA'
    bank_dict['Tyler']='Tyler Medical Center'
    bank_dict['Valley']='Valley Cryobank'
    bank_dict['Xytex']='Xytex'
    bank_dict['Zygen']='Zygen'

    return bank_dict

# Generate dictionary for display of stemmed words
# Key is the Field that appears in the dsr_db database
# column name -- and value is full word that is displayed
# in web-app
def gen_word_dict():
    word_dict={}
    word_dict['educ']='education'
    word_dict['colleg']='college'
    word_dict['econom']='economics'
    word_dict['wavi']='wavy'
    word_dict['protest']='protestant'
    word_dict['cathol']='catholic'
    word_dict['japanes']='japanese'
    word_dict['electr']='electric'
    word_dict['biolog']='biology'
    word_dict['univers']='university'
    word_dict['philosophi']='philosophy'
    word_dict['cornel']='cornell'
    word_dict['histori']='history'
    word_dict['citi']='city'
    word_dict['cathol']='catholic'
    word_dict['softwar']='software'
    word_dict['degre']='degree'
    word_dict['chemistri']='chemistry'
    word_dict['dimpl']='dimple'
    word_dict['polit']='politic'
    word_dict['sibl']='sibling'
    word_dict['graduat']='graduate'
    word_dict['softbal']='softball'
    word_dict['favorit']='favorite'
    word_dict['astrophys']='astrophysics'
    word_dict['famili']='family'
    word_dict['justic']='justice'
    word_dict['languag']='language'
    word_dict['caucas']='caucasian'
    word_dict['curli']='curly'
    word_dict['engin']='engineer'
    word_dict['medic']='medical'
    word_dict['programm']='programming'
    word_dict['educ']='education'
    word_dict['movi']='movie'
    word_dict['militari']='military'
    word_dict['activ']='active'
    word_dict['comput']='compute'
    word_dict['scienc']='science'
    word_dict['manag']='manage'
    word_dict['wavi']='wavy'
    word_dict['blond']='blonde'
    word_dict['chines']='chinese'
    word_dict['colleg']='college'
    word_dict['photographi']='photography'
    word_dict['chiropract']='chirophractor'
    word_dict['restaur']='restaurant'
    word_dict['tenni']='tennis'
    word_dict['injuri']='injury'
    word_dict['retir']='retire'
    word_dict['studi']='study'

    return word_dict